---
abstract: 'Catalyst based application'
author:
  - 'Copyright 2008 OSRC SysInt Team, all rights reserved.'
distribution_type: module
generated_by: 'Module::Install version 0.72'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Artemis-Reports-Web
no_index:
  directory:
    - inc
    - t
requires:
  Artemis::Config: 2.01
  Artemis::Schema: 2.01
  Catalyst::Action::RenderView: 0
  Catalyst::Controller::BindLex: 0
  Catalyst::Controller::HTML::FormFu: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::Session: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::Runtime: 5.7014
  Catalyst::Test: 0
  Catalyst::View::Mason: 0.16
  FindBin: 0
  Getopt::Long: 0
  Hash::Merge: 0
  Pod::Usage: 0
  TAP::Formatter::HTML: 0
  TAP::Parser: 0
  Test::More: 0
  YAML: 0
  parent: 0
  perl: 5.10.0
version: 2.01
